/**
 * Categories for the Order game. Values are approximate but the order within
 * a category is correct. `minGap` is the smallest difference (in the unit)
 * between two items that may appear together, unless their ratio is large.
 */
export interface OrderItem {
  name: string;
  value: number;
}

export interface OrderCategory {
  id: string;
  /** Shown above the list, e.g. "Put these animals in order from lightest to heaviest". */
  question: string;
  /** Unit shown after values, e.g. "kg". Empty for plain numbers and years. */
  unit: string;
  /** Labels for the top and bottom of the list. */
  lowLabel: string;
  highLabel: string;
  /** Two items closer than this (and with a small ratio) never appear together. */
  minGap: number;
  /** Years and atomic numbers are shown without thousands separators. */
  plain?: boolean;
  items: OrderItem[];
}

const item = (name: string, value: number): OrderItem => ({ name, value });

export const CATEGORIES: readonly OrderCategory[] = [
  {
    id: "animals-weight",
    question: "Put these animals in order from lightest to heaviest",
    unit: "kg",
    lowLabel: "Lightest",
    highLabel: "Heaviest",
    minGap: 10,
    items: [
      item("House mouse", 0.02),
      item("Hamster", 0.1),
      item("Rabbit", 2),
      item("House cat", 4.5),
      item("Koala", 9),
      item("Beaver", 20),
      item("Golden retriever", 30),
      item("Wolf", 40),
      item("Chimpanzee", 50),
      item("Cheetah", 55),
      item("Gorilla", 160),
      item("Lion", 190),
      item("Tiger", 220),
      item("Grizzly bear", 300),
      item("Polar bear", 450),
      item("Horse", 500),
      item("Giraffe", 800),
      item("Hippopotamus", 1500),
      item("White rhinoceros", 2300),
      item("Orca", 4000),
      item("African elephant", 6000),
    ],
  },
  {
    id: "countries-population",
    question: "Put these countries in order from smallest to largest population",
    unit: "million people",
    lowLabel: "Fewest people",
    highLabel: "Most people",
    minGap: 5,
    items: [
      item("Iceland", 0.4),
      item("New Zealand", 5.2),
      item("Norway", 5.5),
      item("Switzerland", 8.8),
      item("Sweden", 10.5),
      item("Netherlands", 18),
      item("Australia", 26),
      item("Canada", 40),
      item("Spain", 48),
      item("South Korea", 52),
      item("Italy", 59),
      item("United Kingdom", 68),
      item("Germany", 84),
      item("Turkey", 86),
      item("Egypt", 113),
      item("Japan", 124),
      item("Mexico", 128),
      item("Russia", 144),
      item("Bangladesh", 173),
      item("Brazil", 216),
      item("Nigeria", 224),
      item("Pakistan", 240),
      item("Indonesia", 278),
      item("United States", 340),
      item("China", 1420),
      item("India", 1430),
    ],
  },
  {
    id: "countries-area",
    question: "Put these countries in order from smallest to largest area",
    unit: "km²",
    lowLabel: "Smallest",
    highLabel: "Largest",
    minGap: 400000,
    items: [
      item("Singapore", 730),
      item("Belgium", 31000),
      item("Switzerland", 41000),
      item("Netherlands", 42000),
      item("Portugal", 92000),
      item("United Kingdom", 244000),
      item("New Zealand", 268000),
      item("Italy", 302000),
      item("Germany", 358000),
      item("Japan", 378000),
      item("Spain", 506000),
      item("France", 644000),
      item("Egypt", 1002000),
      item("South Africa", 1221000),
      item("Mongolia", 1564000),
      item("Iran", 1648000),
      item("Indonesia", 1905000),
      item("Mexico", 1964000),
      item("Saudi Arabia", 2150000),
      item("Algeria", 2382000),
      item("Kazakhstan", 2725000),
      item("Argentina", 2780000),
      item("India", 3287000),
      item("Australia", 7692000),
      item("Brazil", 8516000),
      item("China", 9597000),
      item("United States", 9834000),
      item("Canada", 9985000),
      item("Russia", 17098000),
    ],
  },
  {
    id: "planets-diameter",
    question: "Put these planets and moons in order from smallest to largest diameter",
    unit: "km",
    lowLabel: "Smallest",
    highLabel: "Largest",
    minGap: 2000,
    items: [
      item("Ceres", 940),
      item("Eris", 2326),
      item("Pluto", 2377),
      item("Triton", 2707),
      item("Europa", 3122),
      item("The Moon", 3475),
      item("Io", 3643),
      item("Callisto", 4821),
      item("Mercury", 4879),
      item("Titan", 5150),
      item("Ganymede", 5268),
      item("Mars", 6779),
      item("Venus", 12104),
      item("Earth", 12742),
      item("Neptune", 49244),
      item("Uranus", 50724),
      item("Saturn", 116460),
      item("Jupiter", 139820),
    ],
  },
  {
    id: "inventions-year",
    question: "Put these inventions in order from oldest to newest",
    unit: "",
    lowLabel: "Oldest",
    highLabel: "Newest",
    minGap: 15,
    plain: true,
    items: [
      item("Printing press", 1440),
      item("Telescope", 1608),
      item("Steam engine", 1712),
      item("Hot air balloon", 1783),
      item("Electric battery", 1800),
      item("Photography", 1826),
      item("Telegraph", 1837),
      item("Telephone", 1876),
      item("Light bulb", 1879),
      item("Automobile", 1886),
      item("Radio", 1895),
      item("Airplane", 1903),
      item("Television", 1927),
      item("Jet engine", 1937),
      item("Transistor", 1947),
      item("Laser", 1960),
      item("Internet (ARPANET)", 1969),
      item("Mobile phone", 1973),
      item("World Wide Web", 1989),
      item("DVD", 1995),
      item("iPhone", 2007),
    ],
  },
  {
    id: "buildings-height",
    question: "Put these landmarks in order from shortest to tallest",
    unit: "m",
    lowLabel: "Shortest",
    highLabel: "Tallest",
    minGap: 30,
    items: [
      item("Christ the Redeemer", 38),
      item("Colosseum", 48),
      item("Leaning Tower of Pisa", 57),
      item("Sydney Opera House", 65),
      item("Taj Mahal", 73),
      item("Statue of Liberty", 93),
      item("Big Ben", 96),
      item("St Peter's Basilica", 137),
      item("Great Pyramid of Giza", 139),
      item("Washington Monument", 169),
      item("Space Needle", 184),
      item("The Shard", 310),
      item("Chrysler Building", 319),
      item("Eiffel Tower", 330),
      item("Empire State Building", 381),
      item("Willis Tower", 442),
      item("Petronas Towers", 452),
      item("Taipei 101", 508),
      item("One World Trade Center", 541),
      item("CN Tower", 553),
      item("Shanghai Tower", 632),
      item("Burj Khalifa", 828),
    ],
  },
  {
    id: "rivers-length",
    question: "Put these rivers in order from shortest to longest",
    unit: "km",
    lowLabel: "Shortest",
    highLabel: "Longest",
    minGap: 300,
    items: [
      item("Thames", 346),
      item("Po", 652),
      item("Seine", 777),
      item("Loire", 1012),
      item("Rhine", 1230),
      item("Tigris", 1850),
      item("Colorado", 2330),
      item("Murray", 2508),
      item("Ganges", 2525),
      item("Zambezi", 2574),
      item("Euphrates", 2800),
      item("Danube", 2850),
      item("Rio Grande", 3057),
      item("Indus", 3180),
      item("Volga", 3530),
      item("Niger", 4200),
      item("Mekong", 4350),
      item("Amur", 4444),
      item("Congo", 4700),
      item("Yellow River", 5464),
      item("Yenisei", 5539),
      item("Mississippi–Missouri", 6275),
      item("Yangtze", 6300),
      item("Amazon", 6400),
      item("Nile", 6650),
    ],
  },
  {
    id: "mountains-height",
    question: "Put these mountains in order from lowest to highest",
    unit: "m",
    lowLabel: "Lowest",
    highLabel: "Highest",
    minGap: 200,
    items: [
      item("Table Mountain", 1085),
      item("Mount Vesuvius", 1281),
      item("Ben Nevis", 1345),
      item("Mount Kosciuszko", 2228),
      item("Mount Olympus", 2917),
      item("Mount Etna", 3357),
      item("Mount Cook", 3724),
      item("Mount Fuji", 3776),
      item("Mount Kinabalu", 4095),
      item("Mauna Kea", 4207),
      item("Mount Rainier", 4392),
      item("Matterhorn", 4478),
      item("Mont Blanc", 4808),
      item("Elbrus", 5642),
      item("Kilimanjaro", 5895),
      item("Denali", 6190),
      item("Aconcagua", 6961),
      item("Annapurna", 8091),
      item("Cho Oyu", 8188),
      item("Makalu", 8485),
      item("Lhotse", 8516),
      item("Kangchenjunga", 8586),
      item("K2", 8611),
      item("Mount Everest", 8849),
    ],
  },
  {
    id: "elements-atomic-number",
    question: "Put these chemical elements in order from lowest to highest atomic number",
    unit: "",
    lowLabel: "Lowest",
    highLabel: "Highest",
    minGap: 3,
    plain: true,
    items: [
      item("Hydrogen", 1),
      item("Helium", 2),
      item("Lithium", 3),
      item("Carbon", 6),
      item("Nitrogen", 7),
      item("Oxygen", 8),
      item("Neon", 10),
      item("Sodium", 11),
      item("Magnesium", 12),
      item("Aluminium", 13),
      item("Silicon", 14),
      item("Sulfur", 16),
      item("Chlorine", 17),
      item("Argon", 18),
      item("Potassium", 19),
      item("Calcium", 20),
      item("Iron", 26),
      item("Nickel", 28),
      item("Copper", 29),
      item("Zinc", 30),
      item("Silver", 47),
      item("Tin", 50),
      item("Iodine", 53),
      item("Platinum", 78),
      item("Gold", 79),
      item("Mercury", 80),
      item("Lead", 82),
      item("Uranium", 92),
    ],
  },
  {
    id: "fruits-calories",
    question: "Put these fruits in order from fewest to most calories per 100 g",
    unit: "kcal",
    lowLabel: "Fewest calories",
    highLabel: "Most calories",
    minGap: 6,
    items: [
      item("Lemon", 29),
      item("Watermelon", 30),
      item("Strawberry", 32),
      item("Cantaloupe", 34),
      item("Peach", 39),
      item("Papaya", 43),
      item("Orange", 47),
      item("Pineapple", 50),
      item("Apple", 52),
      item("Pear", 57),
      item("Kiwi", 61),
      item("Cherry", 63),
      item("Grape", 69),
      item("Fig", 74),
      item("Pomegranate", 83),
      item("Banana", 89),
      item("Avocado", 160),
      item("Dates", 277),
      item("Coconut", 354),
    ],
  },
  {
    id: "events-year",
    question: "Put these historical events in order from earliest to latest",
    unit: "",
    lowLabel: "Earliest",
    highLabel: "Latest",
    minGap: 15,
    plain: true,
    items: [
      item("Fall of the Western Roman Empire", 476),
      item("Magna Carta signed", 1215),
      item("Black Death reaches Europe", 1347),
      item("Gutenberg prints the Bible", 1455),
      item("Columbus reaches the Americas", 1492),
      item("Shakespeare writes Hamlet", 1600),
      item("Newton publishes the Principia", 1687),
      item("US Declaration of Independence", 1776),
      item("French Revolution begins", 1789),
      item("Battle of Waterloo", 1815),
      item("Darwin publishes On the Origin of Species", 1859),
      item("Eiffel Tower completed", 1889),
      item("Titanic sinks", 1912),
      item("First World War begins", 1914),
      item("Second World War ends", 1945),
      item("First Moon landing", 1969),
      item("Berlin Wall falls", 1989),
      item("Wikipedia launches", 2001),
    ],
  },
];
